### ISSUE TITLE
Not Accurate

### ISSUE THREAD

**Issue by anveshana99** [men-in-stack/The-Third-Eye#1]
Hi, Thanks for sharing this thing. I have tested you app. Its looks good. But  i have found an issue with tracking. Its not accurate sometimes its showing 100 ,200 very fast . I have placed camera on old 100 rupee note . then its showing first 200 then 100. even in new 100 rupee also. Overall app was good. if Possible fix this. Thank you.

**Comment by Shashanksoni06** [comment]
Hello,
Thanks for testing the app and sharing your thoughts on it.
The app is actually showing the value having highest probability. the speed can be reduced by reducing iterations of thread per unit time. Also, constantly trying to improve the accuracy of model. It will be more precise "Gradually".
